feast:
  project: "usm_cc"
  registry: "java/serving/src/main/resources/registry.pb"
  activeStore: online
  stores:
    # Please see https://api.docs.feast.dev/grpc/feast.core.pb.html#Store for configuration options
    - name: online # Name of the store (referenced by active_store)
      type: REDIS # Type of the store. REDIS, REDIS_CLUSTER are available options
      config:  # Store specific configuration. See
        host: localhost
        port: 6379
logging:
  # Audit logging provides a machine readable structured JSON log that can give better
  # insight into what is happening in Feast.
  audit:
    # Whether audit logging is enabled.
    enabled: true
    # Whether to enable message level (ie request/response) audit logging
    messageLogging:
      enabled: false
      # Logging forwarder currently provides a machine readable structured JSON log to an
      # external fluentd service that can give better insight into what is happening in Feast.
      # Accepts console / fluentd as destination
      destination: console
      fluentdHost: localhost
      fluentdPort: 24224