feast:
  project: "ltr_lt"
  registry: "java/serving/src/main/resources/registry.pb"
  activeStore: online
  stores:
    - name: online
      type: REDIS
      config:
        host: localhost
        port: 6379
logging:
    # Audit logging provides a machine readable structured JSON log that can give better
    # insight into what is happening in Feast.
  audit:
      # Whether audit logging is enabled.
    enabled: true
      # Whether to enable message level (ie request/response) audit logging
    messageLogging:
      enabled: false
      # Logging forwarder currently provides a machine readable structured JSON log to an
      # external fluentd service that can give better insight into what is happening in Feast.
      # Accepts console / fluentd as destination
      destination: console
      fluentdHost: localhost
      fluentdPort: 24224