feast:
  project: "ltr_mo"
  registry: "/var/www/feast/java/serving/src/main/resources/registry.pb"
  activeStore: online
  stores:
    - name: online
      type: REDIS
      config:
        host: prod-dsp-redis.slkos6.clustercfg.aps1.cache.amazonaws.com
        port: 6379